apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: krombat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pnz1990/krombat.git
    targetRevision: main
    path: manifests
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: rpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
